DateRangePicker updates
flsy/ui pull request #53
Opened 2021-03-02 10:41 UTC by dtourek

DateRangePicker can show prev month, calendar shows under 'End Time' input

2021-03-03 11:04 UTC, smidhonza commented
me prijde ze se to chova docela podivne...

<img width="575" alt="Screenshot 2021-03-03 at 12 01 41" src="https://user-images.githubusercontent.com/193536/109796439-73df3780-7c18-11eb-8356-2d657fe359cb.png">

<img width="326" alt="Screenshot 2021-03-03 at 12 02 18" src="https://user-images.githubusercontent.com/193536/109796458-793c8200-7c18-11eb-9dbb-fb9af9584df8.png">

<img width="575" alt="Screenshot 2021-03-03 at 12 02 42" src="https://user-images.githubusercontent.com/193536/109796473-7cd00900-7c18-11eb-8cf0-72b9b69497e6.png">

2021-03-03 11:07 UTC, smidhonza commented on src/modules/Form/components/DateRangePicker.tsx
> +  const handleErrorMessage = (prop: keyof IState) => {
`handleErrorMessage` bych to nenazyval, nic to nehandluje

2021-03-03 11:20 UTC, smidhonza requested changes

2021-03-03 11:20 UTC, smidhonza commented on src/modules/Form/components/DateRangePicker.tsx
> +      <Popup isOpen={isShown !== 'none'} onClose={() => showDatePicker('none')} styles={{ left: isShown === 'to' && '50%' }}>
co pouzit nejakou komponentu namisto toho `styles={}` ?

2021-03-03 11:20 UTC, smidhonza commented on src/modules/Form/components/DateRangePicker.tsx
> +      return;
tady bych mozna nedelal return ale ty datumy prohodil, co ty na to?

2021-03-03 11:20 UTC, smidhonza commented on src/modules/DatePicker/components/SelectYearAndMonth.tsx
> +  withPrevMonth: false,
`withPreviousMonth`

2021-03-03 11:20 UTC, smidhonza commented on src/modules/DatePicker/components/SelectYearAndMonth.tsx
> +      <span>{month >= 0 ? year : year - 1}</span>
tohle je nejaky divny, proc to?

2021-03-03 11:20 UTC, smidhonza commented on src/modules/DatePicker/components/SelectYearAndMonth.tsx
> +      <span>{month === -1 ? monthMap[11] : monthMap[month]}</span>
co s eto deje tady? tomu moc nerozumim

2021-03-03 11:20 UTC, smidhonza commented on src/modules/DatePicker/components/SelectYearAndMonth.tsx
> +      <Button link={true} type="button" onClick={() => updateMonth(withPrevMonth ? month + 2 : month + 1, year, setMonth, setYear)} icon={<RightOutlined />} />
tuhle logiku v parametrech bych resil idealne uvnitr ty `updateMonth` funkce, takhle to je dost neprehledny

2021-03-03 11:20 UTC, smidhonza commented on src/modules/DatePicker/DateRangePicker.tsx
> +      <Flex horizontal={true}>
Tohle i neprijde jako stastny reseni, urcite by to slo udelat lip

<img width="557" alt="Screenshot 2021-03-03 at 12 17 57" src="https://user-images.githubusercontent.com/193536/109798180-bace2c80-7c1a-11eb-8e23-92159011a6e7.png">

je to takovy polovicaty

2021-03-03 11:22 UTC, smidhonza commented
cau @dtourek podle me jsi tyhle zmeny mel zase rozdelit do mensich Pull requestu jak si vzdycky rikame, ted se ti tady mele dohromady vic problemu a jejich reseni a prijde mi ze to zase pomalu narusta v jeden obri nekonecnej PR ktery resi vsechno

2021-03-03 21:15 UTC, dtourek commented on src/modules/Form/components/DateRangePicker.tsx
> +      <Popup isOpen={isShown !== 'none'} onClose={() => showDatePicker('none')} styles={{ left: isShown === 'to' && '50%' }}>
jj, dobrej napad

2021-03-03 21:17 UTC, dtourek commented on src/modules/DatePicker/DateRangePicker.tsx
> +      <Flex horizontal={true}>
chapu, predelal jsem to at to vypada hezcejc.

![Screenshot from 2021-03-03 22-16-58](https://user-images.githubusercontent.com/32526698/109873622-49b86480-7c6e-11eb-8a92-5be7210988dc.png)

2021-03-04 13:15 UTC, smidhonza approved these changes

2021-03-04 13:15 UTC, merged