DateRangePicker component for table
flsy/ui pull request #90
Opened 2021-07-02 13:41 UTC by dtourek

new component dateRangePickerOnly which shows only date range calendar picker. Used for table filtering

2021-07-02 13:48 UTC, kolebjak requested changes
Změnil bych název "DateRangePickerOnly" na něco lepšího

2021-07-02 13:48 UTC, kolebjak commented on src/modules/Form/components/DateRangePickerOnly.tsx
> +  const formatStr = `DD.MM.YYYY ${withTimePicker ? 'HH:mm' : ''}`;
```suggestion
  const formatStr = `DD.MM.YYYY${withTimePicker ? ' HH:mm' : ''}`;
```

2021-07-02 13:48 UTC, kolebjak commented on src/modules/Form/components/DateRangePickerOnly.tsx
> +  const formatStr = `DD.MM.YYYY ${withTimePicker ? 'HH:mm' : ''}`;
Ten formatStr by asi taky měl jít posílat v meta konfiguraci

2021-07-02 13:49 UTC, smidhonza commented on src/modules/Form/components/DateRangePickerOnly.tsx
> +  const defaultSelectedValue = value && value.map((v) => moment(v * 1000));
tohle by taky melo chodit z backendu v mate konfiguraci

2021-07-02 13:51 UTC, smidhonza commented on src/modules/Form/components/DateRangePickerOnly.tsx
> +const now = moment();
tohle by melo byt uvnitr komponenty si myslim

2021-07-07 08:51 UTC, smidhonza commented on src/modules/DatePicker/RangePicker.tsx
> +  const formatStr = formatDatePickerTime(format, withTimePicker);
To `formatDatePickerTime` je mega divna funkce,

Tady bych to pro vetsi citelnost predelal na:
```
const formatStr = format || formatDatePickerTime(withTimePicker);
```

2021-07-07 08:51 UTC, smidhonza commented on src/modules/DatePicker/RangePicker.tsx
> +  const formatStr = formatDatePickerTime(format, withTimePicker);
a pak prejmenoval to `formatDatePickerTime` na `defaultDateFormat`

2021-07-07 11:16 UTC, dtourek commented on src/modules/DatePicker/RangePicker.tsx
> +  const formatStr = formatDatePickerTime(format, withTimePicker);
hmm, jo mas pravdu, tak se ti lip cte a ta funkce nema 2 divny parametry. diky

2021-07-07 14:19 UTC, smidhonza approved these changes

2021-07-07 18:28 UTC, merged